version: '3.7'

services:
  prometheus:
    image: 'prom/prometeus'
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./obsevability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: 'grafana/grafana'
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  apiteste: {}